version: '3'

includes:
  envx:
    taskfile: ./app/Taskfile.yaml
    dir: ./app

tasks:
  install:
    desc: Install all dependencies (Node + Python)
    cmds:
      - mise install
      - pnpm install
      - task envx:install
