package runner

import (
	"errors"
	"os"
	"os/exec"
	"syscall"
)

// forwardedSignals are the signals Run watches. Catching them keeps envx alive
// (rather than dying and orphaning the child) so it can wait for the child and
// mirror its exit; each is then relayed to the child, subject to the interactive
// guard in shouldForward. The same signal is always forwarded unchanged, so a
// child is never sent a signal the user did not.
var forwardedSignals = []os.Signal{
	os.Interrupt,    // SIGINT  — Ctrl+C
	syscall.SIGTERM, // supervisors' default stop signal
	syscall.SIGHUP,  // controlling terminal closed
	syscall.SIGQUIT, // Ctrl+\
}

// ttyDeliveredSignals are generated by the terminal line discipline (Ctrl+C,
// Ctrl+\) and delivered to the whole foreground process group at once, so an
// interactive child already receives them directly from the tty. Relaying them
// again would double-deliver — e.g. turning one Ctrl+C into two, which some
// programs treat as "force quit". They are forwarded only when envx is not
// attached to a terminal (a supervisor signalling envx alone); SIGTERM/SIGHUP,
// which the tty does not broadcast to the group, are always forwarded.
var ttyDeliveredSignals = map[os.Signal]bool{
	os.Interrupt:    true, // SIGINT  — Ctrl+C
	syscall.SIGQUIT: true, // SIGQUIT — Ctrl+\
}

// exitCode extracts the child's exit code, mapping a signal-terminated child to
// the shell convention 128+signum (e.g. 130 for SIGINT) instead of the -1 that
// ExitCode reports for a signaled process.
func exitCode(exitErr *exec.ExitError) int {
	if code := exitErr.ExitCode(); code >= 0 {
		return code
	}
	if ws, ok := exitErr.Sys().(syscall.WaitStatus); ok && ws.Signaled() {
		return 128 + int(ws.Signal())
	}
	return 1
}

// startFailureCode maps a failure to start the child to the shell's conventional
// exit code: 127 when the command was not found on PATH, and 126 when it was
// found but could not be executed (for example, a permission error).
func startFailureCode(err error) int {
	if errors.Is(err, exec.ErrNotFound) {
		return 127
	}
	return 126
}

// shouldForward reports whether a received signal should be relayed to the
// child. Terminal-generated signals (see ttyDeliveredSignals) are skipped when
// envx runs interactively because the tty already delivered them to the child's
// process group; every other case forwards, so a child still receives signals
// directed at envx alone.
func shouldForward(sig os.Signal, interactive bool) bool {
	if interactive && ttyDeliveredSignals[sig] {
		return false
	}
	return true
}

// mapToEnv converts a key-value map into the os.Environ() slice format
// (["KEY=VALUE", ...]) suitable for exec.Cmd.Env.
func mapToEnv(m map[string]string) []string {
	result := make([]string, 0, len(m))
	for k, v := range m {
		keyValuePair := k + "=" + v
		result = append(result, keyValuePair)
	}
	return result
}
