package runner

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"syscall"

	"github.com/go-envx/envx/app/internal/exitcode"
)

// forwardedSignals are the signals Run watches. Catching them keeps envx alive
// (rather than dying and orphaning the child) so it can wait for the child and
// mirror its exit; each is then relayed to the child, subject to the interactive
// guard in shouldForward. The same signal is always forwarded unchanged, so a
// child is never sent a signal the user did not.
var forwardedSignals = []os.Signal{
	os.Interrupt,    // SIGINT  — Ctrl+C
	syscall.SIGTERM, // supervisors' default stop signal
	syscall.SIGHUP,  // controlling terminal closed
	syscall.SIGQUIT, // Ctrl+\
}

// ttyDeliveredSignals are generated by the terminal line discipline (Ctrl+C,
// Ctrl+\) and delivered to the whole foreground process group at once, so an
// interactive child already receives them directly from the tty. Relaying them
// again would double-deliver — e.g. turning one Ctrl+C into two, which some
// programs treat as "force quit". They are forwarded only when envx is not
// attached to a terminal (a supervisor signalling envx alone); SIGTERM/SIGHUP,
// which the tty does not broadcast to the group, are always forwarded.
var ttyDeliveredSignals = map[os.Signal]bool{
	os.Interrupt:    true, // SIGINT  — Ctrl+C
	syscall.SIGQUIT: true, // SIGQUIT — Ctrl+\
}

// Run spawns the specified command as a child process with the ready-to-inject
// environment supplied in Params.Env. It stays deliberately transparent: rather
// than binding the child's lifetime to a context and
// force-killing it, Run relays received signals to the child and lets the child
// decide when to exit, then mirrors its exit status — so `envx run -- cmd`
// behaves just like running `cmd` directly. Returns nil on success, an
// *exitcode.Error carrying the child's code (128+signum when the child was
// terminated by a signal) so main.go can propagate it, or a wrapped error when
// the process fails to start.
func Run(args []string, p Params) error {
	if len(args) == 0 {
		return errors.New("no command specified")
	}

	normalizeParams(&p)

	// exec.Command (not CommandContext) is deliberate: envx stays transparent by
	// forwarding signals to the child and mirroring its exit status, so the child
	// owns its own shutdown. Binding it to a context would let cancellation
	// SIGKILL it out from under a graceful shutdown — the surprise we avoid here.
	//nolint:gosec,noctx // intentional; see comment above
	cmd := exec.Command(args[0], args[1:]...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = p.Stdout
	cmd.Stderr = p.Stderr
	cmd.Env = mapToEnv(p.Env)

	if err := cmd.Start(); err != nil {
		// Mirror a shell: report the failure and exit with its conventional code
		// (127 not-found, 126 found-but-not-executable) rather than the generic
		// runtime code, so scripts wrapping `envx run` can branch on it.
		_, _ = fmt.Fprintf(p.Stderr, "envx: %v\n", err)
		return &exitcode.Error{Code: startFailureCode(err)}
	}

	// Relay signals to the child until it exits. Installing these handlers also
	// keeps envx alive (rather than dying on the signal and orphaning the child)
	// so it can wait for the child and mirror its final status. Terminal signals
	// the tty already delivered to an interactive child are not re-forwarded.
	interactive := stdinIsTerminal()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, forwardedSignals...)
	defer signal.Stop(sigCh)

	waitDone := make(chan struct{})
	go func() {
		for {
			select {
			case sig := <-sigCh:
				if shouldForward(sig, interactive) {
					_ = cmd.Process.Signal(sig)
				}
			case <-waitDone:
				return
			}
		}
	}()

	err := cmd.Wait()
	close(waitDone)

	if err == nil {
		return nil
	}
	if exitErr, ok := errors.AsType[*exec.ExitError](err); ok {
		return &exitcode.Error{Code: exitCode(exitErr)}
	}
	return fmt.Errorf("running command: %w", err)
}

// exitCode extracts the child's exit code, mapping a signal-terminated child to
// the shell convention 128+signum (e.g. 130 for SIGINT) instead of the -1 that
// ExitCode reports for a signaled process.
func exitCode(exitErr *exec.ExitError) int {
	if code := exitErr.ExitCode(); code >= 0 {
		return code
	}
	if ws, ok := exitErr.Sys().(syscall.WaitStatus); ok && ws.Signaled() {
		return 128 + int(ws.Signal())
	}
	return 1
}

// startFailureCode maps a failure to start the child to the shell's conventional
// exit code: 127 when the command was not found on PATH, and 126 when it was
// found but could not be executed (for example, a permission error).
func startFailureCode(err error) int {
	if errors.Is(err, exec.ErrNotFound) {
		return 127
	}
	return 126
}

// shouldForward reports whether a received signal should be relayed to the
// child. Terminal-generated signals (see ttyDeliveredSignals) are skipped when
// envx runs interactively because the tty already delivered them to the child's
// process group; every other case forwards, so a child still receives signals
// directed at envx alone.
func shouldForward(sig os.Signal, interactive bool) bool {
	if interactive && ttyDeliveredSignals[sig] {
		return false
	}
	return true
}

// stdinIsTerminal reports whether standard input is a character device, the
// lightweight, dependency-free proxy for "running attached to a terminal" that
// tells Run whether the tty will deliver SIGINT/SIGQUIT to the child directly. A
// non-tty character device such as /dev/null is a harmless false positive: at
// worst envx skips forwarding a SIGINT a supervisor would otherwise send itself.
func stdinIsTerminal() bool {
	info, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

// mapToEnv converts a key-value map into the os.Environ() slice format
// (["KEY=VALUE", ...]) suitable for exec.Cmd.Env.
func mapToEnv(m map[string]string) []string {
	result := make([]string, 0, len(m))
	for k, v := range m {
		result = append(result, k+"="+v)
	}
	return result
}
